export const initialState = {
  id: 'UDp7KNNtqoBFG_-VAgPHS',
  name: 'New Design1',
  sides: {
    back: {
      bgUrl:
        'https://dev-minio-api.busycube.net/coolprint-static/brazil_back-1689766239261.webp',
      objects: [
        {
          x: 194.5,
          y: 200,
          id: 'MfCP3sjO4m1YbssJB3y4E',
          url: '',
          fill: '#DBCAA7',
          name: 'groupable',
          text: 'Text here',
          type: 'text',
          align: 'left',
          shape: 'normal',
          width: 211,
          height: 50,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          visible: true,
          fontSize: 50,
          rotation: 0,
          draggable: false,
          fontStyle: 'bold',
          resizable: true,
          fontFamily: 'Roboto CoolPrint',
          selectable: true,
          showInExport: true,
          letterSpacing: 0,
          shapeStrength: 10,
          fontFamilyName: '',
          shadowSettings: null,
          strokeSettings: null,
        },
      ],
      previewUrl:
        'https://dev-minio-api.busycube.net/coolprint-static/UDp7KNNtqoBFG_-VAgPHS_preview_back-1711526966635.png',
      printableArea: {
        size: {
          width: 250,
          height: 353.5,
        },
        position: {
          x: 175,
          y: 174.75,
        },
      },
    },
    front: {
      bgUrl:
        'https://dev-minio-api.busycube.net/coolprint-static/brazil_front_base-1689766239260.webp',
      objects: [
        {
          x: 192.49999999999972,
          y: 193.6811118084357,
          id: 'UXsArOdtb9vACr-gq6C58',
          url: 'https://dev-minio-api.busycube.net/coolprint-static/brazil_right_logo-1690547762698.png',
          fill: '',
          name: 'groupable',
          type: 'img',
          extra: {
            name: 'left logo',
            type: 'img',
          },
          width: 125,
          height: 125,
          scaleX: 0.4705681065668069,
          scaleY: 0.47056810656680675,
          opacity: 1,
          visible: true,
          fileName: 'Left Logo',
          rotation: 0,
          draggable: false,
          resizable: true,
          selectable: true,
          uploadable: false,
          showInExport: true,
        },
        {
          x: 317.5894933395746,
          y: 162.68111180843607,
          id: 'tJBVtY1T_JABpnpm4SqFa',
          url: 'https://dev-minio-api.busycube.net/coolprint-static/brazil_left_logo-1689766239260.png',
          fill: '',
          name: 'groupable',
          type: 'img',
          extra: {
            name: 'right logo',
            type: 'img',
          },
          width: 125,
          height: 125,
          scaleX: 0.850652751661124,
          scaleY: 0.8506527516611233,
          opacity: 1,
          visible: true,
          fileName: 'Right Logo',
          rotation: 0,
          draggable: false,
          resizable: true,
          selectable: true,
          uploadable: false,
          showInExport: true,
        },
        {
          x: 194.5,
          y: 288,
          id: 'tsWYh-Mf2cvjCaie51YUE',
          url: '',
          fill: '#FFFFFF',
          name: 'groupable',
          text: 'Text here',
          type: 'text',
          align: 'left',
          shape: 'normal',
          width: 211,
          height: 50,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          visible: true,
          fontSize: 50,
          rotation: 0,
          draggable: false,
          fontStyle: 'bold',
          resizable: true,
          fontFamily: 'Roboto CoolPrint',
          selectable: true,
          showInExport: true,
          letterSpacing: 0,
          shapeStrength: 10,
          fontFamilyName: '',
          shadowSettings: null,
          strokeSettings: null,
        },
        {
          x: 262.5,
          y: 357,
          id: 'zg277XOI3jEpoBhnor9xO',
          url: 'https://dev-minio-api.busycube.net/cdn/artwork/20230818/stickers/GotThis.svg',
          fill: '',
          name: 'groupable',
          type: 'art',
          extra: {
            name: 'GotThis',
            type: 'art',
          },
          width: 75,
          height: 86,
          scaleX: 1,
          scaleY: 1,
          opacity: 1,
          visible: true,
          fileName: 'GotThis',
          rotation: 0,
          draggable: false,
          resizable: true,
          selectable: true,
          uploadable: false,
          showInExport: true,
        },
      ],
      previewUrl:
        'https://dev-minio-api.busycube.net/coolprint-static/UDp7KNNtqoBFG_-VAgPHS_preview_front-1711526965784.png',
      printableArea: {
        size: {
          width: 250,
          height: 353.5,
        },
        position: {
          x: 175,
          y: 174.75,
        },
      },
    },
  },
  width: 1200,
  height: 1406,
  customer: 'person',
  template: '',
  memberList: [],
  centerTeamObjects: true,
};
